import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import classes from './index.module.css'
 import Link from 'next/link'
 import imageOne from '../public/imageOne.jpeg'
 import imageTwo from '../public/imageTwo.jpeg'
 import imageThree from '../public/imageThree.jpeg'
 import imageFour from '../public/imageFour.jpeg'
 import Footer from '../conponent/footer'
 

export default function Home() {
  return (
    <>
      <Head>
        <title>Rosystepp App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes.header}>
        <h1>Rosy Step Application</h1>
        <div className={classes.gallery}>
          <div className={classes.figure}>
            <Image
              src={imageOne}
              alt="email"
              width={400}
              height={200}
            />
          </div>
          <div className={classes.figure}>
            <Image
              src={imageTwo}
              alt="email"
              width={400}
              height={200}
            />
          </div>
          <div className={classes.figure}>
            <Image
              src={imageThree}
              alt="email"
              width={400}
              height={200}
            />
          </div>
          <div className={classes.figure}>
            <Image
              src={imageFour}
              alt="email"
              width={400}
              height={200}
            />
          </div>
        </div>
        <div className={classes.rosy}>
          <p>Rosystep Software engineers</p>
          <Link href='https://rosysteps.netlify.app/' target='_blank'> <button>Enroll Now</button></Link>
         
        </div>
        <Footer/>
      </div>
    </>
  )
}
